### ISSUE TITLE
Validate existence of asset feeds before bundling?

### ISSUE THREAD

**Issue by trygve-lie** [asset-pipe/asset-pipe-build-server#30]
The process of making a bundle consist of posting an array of references to asset feeds one want to become a bundle. 

When posting the references to asset feeds to build a bundle there is now no validation if these references actually exist. 

Should we have a strict check on this and check that the asset feeds does exist?

There is two approaches to this:

 - If an asset feed is not present, ignore it and make a build on what we have. This reports OK to the client requesting the build.
- If an asset feed is not present, stop the build process and do not build anything. This reports Error to the client requesting the build.

The first has the benefit that we can bundle something no matter what. In a system where components are composed this might can handle that the assets of one component is missing, but the rest if working. The drawback is that we let some assets fail.

The second has the benefit that we will never get bundles missing something. The benefit of this is always complete bundles. The drawback is that if one asset feed is missing we will not be able to build a bundle at all.

**Comment by digitalsadhu** [comment]
Feeds must now be present otherwise bundling fails.
