### ISSUE TITLE
public path requires trailing slash

### ISSUE THREAD

**Issue by runeh** [asset-pipe/asset-pipe-build-server#33]
Given 

```
const Assets = require('asset-pipe-build-server');
const assets = new Assets({
    publicPath: path.resolve(__dirname, 'local-assets')
});
app.use('/', assets.router);
```

This fails, because the assets class expectes a trailing slash, and there isn't one. So it generates wrong URLs.

**Comment by trygve-lie** [comment]
This is a bit different after the last changes so should really not be an issue any more.

There will also be a feature where one can provide an override of the host/path to the files so one can get responses back from the asset server where the uri to the files point to ex its location in a CDN.
