### ISSUE TITLE
Make it possible to override host/path to asset feeds and bundles

### ISSUE THREAD

**Issue by trygve-lie** [asset-pipe/asset-pipe-build-server#47]
When making a bundle or uploading a asset feed the build server responds with a URI to the asset feed or bundle. In a production environment one will probably not let the asset build server serve these directly (in our case at FINN this will be served from our CDN).

It must be possible to override host/path so an alternative URI to the asset feeds and bundles are returned in the response.

**Comment by digitalsadhu** [comment]
With optimistic bundling, the client must calculate the location and filename of any produced bundles itself directly from the asset feed hashes.
