### ISSUE TITLE
Implement build of JS bundle permutations when an asset-feed changes

### ISSUE THREAD

**Issue by trygve-lie** [asset-pipe/asset-pipe-build-server#69]
We want to introduce building of permutations of js bundles. This task is to implement this when an asset-feed changes.

This is the flow which should be implemented:
![Flow](https://raw.githubusercontent.com/asset-pipe/asset-pipe-build-server/master/docs/flow-feed-change.2017.05.19.png)

A change in an asset-feed are when a dependency is added, removed or changes in a service that uploads assets to the asset-build server. An asset-feed can be used by multiple services that will request js bundles to be build, in other words; an assed feed can be used in multiple permutations.

The main goal here is that when an asset-feed is uploaded to the asset-build server, the asset-build need to find all usages of the asset-feed and create new bundles for each usage.

Some sub tasks we need to perform this:
- [ ] Introduce folders for each type of persisted files in the storage - #71
- [ ] Introduce a metafile for each "asset-feed-id" - #72

**Comment by digitalsadhu** [comment]
Done
