### ISSUE TITLE
Implement build of JS bundle permutations when an permutation changes

### ISSUE THREAD

**Issue by trygve-lie** [asset-pipe/asset-pipe-build-server#70]
We want to introduce building of permutations of js bundles. This task is to implement this when an permutation changes.

This is the flow which should be implemented:
![Flow](https://raw.githubusercontent.com/asset-pipe/asset-pipe-build-server/master/docs/flow-permutation-change.2017.05.19.png)

A change in a permutation are when an service which requests builds of a set of asset-feeds changes. In other words; if a service adds, removes or change order of which asset-feeds it wants in a build, its an change in a permutation.

The main goal here is that when an change in an permutation is requested on the asset-build server, the asset-build need to build a new bundle.

Some sub tasks we need to perform this:
 - [ ] Introduce folders for each type of persisted files in the storage - #71

**Comment by digitalsadhu** [comment]
Done
