### ISSUE TITLE
Introduce folders for each type of persisted files in the storage

### ISSUE THREAD

**Issue by trygve-lie** [asset-pipe/asset-pipe-build-server#71]
For building permutations upon changes in asset-feeds of the permutation feed, we need to keep some meta info somewhere. We will store this in plain json files in the storage. Plus, the bundles and asset-feeds will also be kept in the storage.

To keep the storage clean; introduce in the storage which are intended to store each type of file. Should be one folder for asset-feeds, one for js-bundles, one for meta files fo asset-feeds and one for meta files for permutations.

**Comment by digitalsadhu** [comment]
Done. Not quite as described here. Favoured backwards compatibility so wherever possible have not adjusted folder structure just yet. This could be revisited later
